import { Inter } from '@next/font/google'
import Head from 'next/head'
import FooterComponent from '../components/FooterComponent'
import HeaderComponent from '../components/header'
import HomeComponent from '../components/HomeComponent'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ride Sharing App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="body-wrap boxed-container">
		<HeaderComponent />
        <main>
		<HomeComponent />
        </main>
		<FooterComponent />
        </div>
      </main>
    </>
  )
}
